print('Programa desenvolvido por @MateusMedeiros. ')
print()
print('Calcular Fio de Cobre necessário para revestir uma casa.')
lado1=float(input('Digite o maior comprimento da casa em metros, por exemplo 2.5 (2 Metros e Meio): '))
lado2=float(input('Digite a maior largura da casa em metros, por exemplo 3.5 (3 Metros e Meio): '))
formula=(lado1**2) + (lado2**2)
formula2=(formula**(1/2))
print('Vamos Calcular! ')
print()
print('Você precisará de aproximadamente %7.2f metros de fio de cobre! ' % formula2)
