sexo=input('Digite seu sexo, sendo (M) para masculino ou (F) para feminino:')
idade=int(input('Digite a sua idade:'))
if sexo == 'M' or sexo == 'm':
    if idade >=18 and idade <70:
        print('Você é obrigado a votar.')
        print()
        print('Você tem o direito de conduzir veiculos.')
        print()
        print('Você já é um cidadão com idade penal.')
        print()
        print('Você deve estar em dia com as obrigações militares.')
    elif idade>=16 and idade <18:
        print('Seu voto é facutativo.')
        print()
        print('Você não tem idade para conduzir veiculos')
        print()
        print('Você não tem idade penal.')
        print()
        print('Você ainda não tem obrigações militares.')
    elif idade <16:
        print('Você nao vota.')
        print()
        print('Você não tem idade para conduzir veiculos')
        print()
        print('Você não tem idade penal.')
        print()
        print('Você ainda não tem obrigações militares.')
    elif idade >=70:
        print('Você pode conduzir veiculo.')
        print()
        print('Seu voto é facutativo.')
        print()
        print('Você tem idade penal.')
        print()
elif sexo == 'f' or sexo =='F':
    if idade>=18 and idade<70:
        print('Você é obrigada a votar.')
        print()
        print('Você tem o direito de conduzir veiculos.')
        print()
        print('Você já é um cidadão com idade penal.')
        print()
        print('Você não tem obrigações militares.')
    elif idade >=16 and idade <18:
        print('Seu voto é facutativo.')
        print()
        print('Você não tem o direito de conduzir veiculos.')
        print()
        print('Você não é um cidadão com idade penal.')
        print()
        print('Você não tem obrigações militares.')
    elif idade<16:
        print('Você não vota.')
        print()
        print('Você não tem o direito de conduzir veiculos.')
        print()
        print('Você não é um cidadão com idade penal.')
        print()
        print('Você não tem obrigações militares.')
    elif idade>70:
        print('Seu voto é facutativo.')
        print()
        print('Você tem o direito de conduzir veiculos.')
        print()
        print('Você já é um cidadão com idade penal.')
        print()
        print('Você não tem obrigações militares.')
        
