import random
x=1
while x==1:
    a=input('Dê enter para continuar. ')
    b=input('Digite seu nome: ')
    print('Vamos ao sorteio.')
    x1=random.randint(1,6)
    if x1==1:
        print('#########')
        print('#       #')
        print('#   *   #')
        print('#       #')
        print('#########')
    elif x1==2:
        print('#########')
        print('# *     #')
        print('#       #')
        print('#     * #')
        print('#########')
    elif x1 ==3:
        print('#########')
        print('# *     #')
        print('#   *   #')
        print('#     * #')
        print('#########')
    elif x1 ==4:
        print('#########')
        print('# *   * #')
        print('#       #')
        print('# *   * #')
        print('#########')
    elif x1==5:
        print('#########')
        print('# *   * #')
        print('#   *   #')
        print('# *   * #')
        print('#########')
    elif x1==6:
        print('#########')
        print('# *   * #')
        print('# *   * #')
        print('# *   * #')
        print('#########')
        print()
        print()
    x2=random.randint(1,6)
    if x2==1:
        print('#########')
        print('#       #')
        print('#   *   #')
        print('#       #')
        print('#########')
    elif x2==2:
        print('#########')
        print('# *     #')
        print('#       #')
        print('#     * #')
        print('#########')
    elif x2 ==3:
        print('#########')
        print('# *     #')
        print('#   *   #')
        print('#     * #')
        print('#########')
    elif x2 ==4:
        print('#########')
        print('# *   * #')
        print('#       #')
        print('# *   * #')
        print('#########')
    elif x2==5:
        print('#########')
        print('# *   * #')
        print('#   *   #')
        print('# *   * #')
        print('#########')
    elif x2==6:
        print('#########')
        print('# *   * #')
        print('# *   * #')
        print('# *   * #')
        print('#########')
        print()
        print()
    pontos1=x1+x2
    print('%s fez %d pontos. ' % (b,pontos1))
    x3=random.randint(1,6)
    if x3==1:
        print('#########')
        print('#       #')
        print('#   *   #')
        print('#       #')
        print('#########')
    elif x3==2:
        print('#########')
        print('# *     #')
        print('#       #')
        print('#     * #')
        print('#########')
    elif x3 ==3:
        print('#########')
        print('# *     #')
        print('#   *   #')
        print('#     * #')
        print('#########')
    elif x3 ==4:
        print('#########')
        print('# *   * #')
        print('#       #')
        print('# *   * #')
        print('#########')
    elif x3==5:
        print('#########')
        print('# *   * #')
        print('#   *   #')
        print('# *   * #')
        print('#########')
    elif x3==6:
        print('#########')
        print('# *   * #')
        print('# *   * #')
        print('# *   * #')
        print('#########')
        print()
        print()
    x4=random.randint(1,6)
    if x4==1:
        print('#########')
        print('#       #')
        print('#   *   #')
        print('#       #')
        print('#########')
    elif x4==2:
        print('#########')
        print('# *     #')
        print('#       #')
        print('#     * #')
        print('#########')
    elif x4 ==3:
        print('#########')
        print('# *     #')
        print('#   *   #')
        print('#     * #')
        print('#########')
    elif x4 ==4:
        print('#########')
        print('# *   * #')
        print('#       #')
        print('# *   * #')
        print('#########')
    elif x4==5:
        print('#########')
        print('# *   * #')
        print('#   *   #')
        print('# *   * #')
        print('#########')
    elif x4==6:
        print('#########')
        print('# *   * #')
        print('# *   * #')
        print('# *   * #')
        print('#########')
        print()
        print()
    pontos2=x3+x4
    print()
    print('O computador fez fez %d pontos. ' % pontos2)
    if pontos1>pontos2:
        print('%s venceu. ' % b)
    elif pontos2>pontos1:
        print('O computador venceu.')
    else:
        print('Empate.')
    print()
    print('Deseja jogar novamente? Digite 1 para sim e 2 para não.')
    x=int(input())
    print()
